name: productivity_tips_ads_flutter
description: >-
  Appli Flutter cross-platform (Android + iOS) qui affiche des phrases
  de motivation, enregistre le ressenti de l'utilisateur et affiche des
  graphes de synthèse, avec bannière AdMob pour revenu passif.

publish_to: "none"

version: 1.2.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mobile_ads: ^7.0.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^17.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
